### ISSUE TITLE
Set env variables in dependency aoe_technology_radar

### ISSUE THREAD

**Issue by santiago5020gg** [AOEpeople/techradar#174]
There is no way to set env variables in node_modules for aoe_technology_radar wich is responsible for generate the build folder with the static files unless you modify directly in node_modules/aoe_technology_radar and creates an .env variable definying PUBLIC_URL=/build wich of course not working if you don't set to /build. Even setting the env in the root directory don't do anything. Just setting in node_modules/aoe_technology_radar and creates an .env variable definying PUBLIC_URL=/build

**Comment by bastianccm** [comment]
Hi @santiago5020gg,

this repository is not intended for extension, as it is an active project itself.
If you want to build your own radar, please use https://github.com/AOEpeople/aoe_technology_radar directly. You can take this repository as a reference.
