### ISSUE TITLE
Social icons not displayed

### ISSUE THREAD

**Issue by panzerfahrer** [AOEpeople/techradar#26]
The social icons in the footer appear to be broken. Maybe an issue with the icon font?

**Comment by bmsuseluda** [comment]
Will be fixed with the upcomming version 4 (https://github.com/AOEpeople/aoe_technology_radar/commit/29d9b9ef609ad4b41775bd65399b262acb4f0192)

**Comment by bmsuseluda** [comment]
Will be fixed with the upcomming version 4 (https://github.com/AOEpeople/aoe_technology_radar/commit/8884ee3931cf7245fc45a2a222bd326934d79fc6)
