### ISSUE TITLE
node-sass version depends on Python 2

### ISSUE THREAD

**Issue by Karreg** [AOEpeople/techradar#38]
node-sass 4, dependency of techradar, depends on python2 (see https://github.com/sass/node-sass/issues/2877). Hence it's not working anymore on recent systems.
Is there a plan to migrate to node-sass 5?

**Comment by bmsuseluda** [comment]
Hello Karreg, we updated the stack of https://github.com/AOEpeople/aoe_technology_radar and don't use node-sass anymore.
You can test it with our upcomming version https://github.com/AOEpeople/techradar/tree/radar-2021-01-01

**Comment by Karreg** [comment]
Hello,

It is fixed indeed. Thanks.
However, the whole thing does not work as descrived in the Readme. I guess the documentation is outdated. We only get 404 errors :/

**Comment by bmsuseluda** [comment]
Hello @Karreg i updated the documentation to make it more clear. Please have a look. If it doesn't work either, please be more specific what you are doing and maybe post the console output, so that i can help you properly.

**Comment by Karreg** [comment]
Hello,

I have found the needed information in the aoe_technology_radar module:

```
## Run a prepared static version
In most cases you have the tech radar available at `/techradar`, and for reasons want all correct pages to be accessible.

Until this setup improves, you can use the following way to generate the correct tech radar:


yarn aoe_technology_radar-generateJson
PUBLIC_URL=/techradar yarn aoe_technology_radar-buildRadar
yarn aoe_technology_radar-createStaticFiles
cp -r build techradar


(This is rather workaroundish for now, but does the job.)
```

With that information, I was able to generate and see the techradar, however, this is really an issue to easily publish a radar with Gitlab Pages for example. I should still be able to find a workaround with another index page that forwards in a subfolder.

So it's OK for me, I'll still be looking at this code for improvements on building and releasing a techradar :)

**Comment by bmsuseluda** [comment]
The information you have posted isoutdated. Please have a look at https://github.com/AOEpeople/aoe_technology_radar
There it is described how to customize the tech radar. One of the customization is "Host the application under a sub path".
I think this is what you need to host it with gitlab pages.

**Comment by Karreg** [comment]
Thanks for the update, I will have a look into it.
